### ISSUE TITLE
Make dataset error

### ISSUE THREAD

**Issue by Augus-smile** [xmfbit/captcha-recognition#2]

**Comment by Augus-smile** [comment]
Hi, when i training the model, it occurs a mistake  about 
Traceback (most recent call last):
  File "main.py", line 61, in <module>
    mean=mean, std=std)
  File "/home/xxxxxx/captcha-recognition/dataset.py", line 42, in __init__
    label_seq = [int(x)+1 for x in label_seq]
  File "/home/xxxxxx/captcha-recognition/dataset.py", line 42, in <listcomp>
    label_seq = [int(x)+1 for x in label_seq]
ValueError: invalid literal for int() with base 10: 'r'

**Comment by Augus-smile** [comment]
it's ok!
